/*----- PROTECTED REGION ID(ChimeraTKExample2.h) ENABLED START -----*/
//=============================================================================
//
// file :        ChimeraTKExample2.h
//
// description : Include file for the ChimeraTKExample2 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef ChimeraTKExample2_H
#define ChimeraTKExample2_H

#include <tango.h>
#include <AttributProperty.h>
#include <TangoAdapter.h>
//#include "MyApplication.h"


/*----- PROTECTED REGION END -----*/	//	ChimeraTKExample2.h

/**
 *  ChimeraTKExample2 class description:
 *    Test of TangoAdapterfor ChimeraTK
 */

namespace ChimeraTKExample2_ns
{
/*----- PROTECTED REGION ID(ChimeraTKExample2::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	ChimeraTKExample2::Additional Class Declarations

class ChimeraTKExample2 : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(ChimeraTKExample2::Data Members) ENABLED START -----*/

//	Add your own data members
private: 
	ChimeraTK::TangoAdapter* adapter;
	//ExampleApp *theExampleApp;
/*----- PROTECTED REGION END -----*/	//	ChimeraTKExample2::Data Members

//	Device property data members
public:
	//	AttributList:	AttributList
	vector<string>	attributList;
	//	DMapFilePath:	DMapFilePath
	string	dMapFilePath;


//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	ChimeraTKExample2(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	ChimeraTKExample2(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	ChimeraTKExample2(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~ChimeraTKExample2() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : ChimeraTKExample2::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);


	//--------------------------------------------------------
	/**
	 *	Method      : ChimeraTKExample2::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : ChimeraTKExample2::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(ChimeraTKExample2::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	ChimeraTKExample2::Additional Method prototypes
};

/*----- PROTECTED REGION ID(ChimeraTKExample2::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	ChimeraTKExample2::Additional Classes Definitions

}	//	End of namespace

#endif   //	ChimeraTKExample2_H
