/*----- PROTECTED REGION ID(TestChimeraTK2.h) ENABLED START -----*/
//=============================================================================
//
// file :        TestChimeraTK2.h
//
// description : Include file for the TestChimeraTK2 class
//
// project :
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TestChimeraTK2_H
#define TestChimeraTK2_H

#include <tango/tango.h>
#include <ChimeraTK/TangoAdapter.h>

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2.h

/**
 *  TestChimeraTK2 class description:
 *    Test of TangoAdapterfor ChimeraTK
 */

namespace TestChimeraTK2_ns
{
/*----- PROTECTED REGION ID(TestChimeraTK2::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::Additional Class Declarations

class TestChimeraTK2 : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TestChimeraTK2::Data Members) ENABLED START -----*/

//	Add your own data members
	ChimeraTK::TangoAdapter* tangoAdapter;
/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::Data Members

//	Device property data members
public:
	//	AttributList:	AttributList
    std::vector<std::string>	attributList;
	//	DMapFilePath:	DMapFilePath
    std::string	dMapFilePath;


//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TestChimeraTK2(Tango::DeviceClass *cl,std::string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TestChimeraTK2(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TestChimeraTK2(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~TestChimeraTK2() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TestChimeraTK2::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(std::vector<long> &attr_list);


	//--------------------------------------------------------
	/**
	 *	Method      : TestChimeraTK2::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : TestChimeraTK2::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TestChimeraTK2::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TestChimeraTK2::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::Additional Classes Definitions

}	//	End of namespace

#endif   //	TestChimeraTK2_H
