/*----- PROTECTED REGION ID(TestChimeraTK2StateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TestChimeraTK2StateMachine.cpp
//
// description : State machine file for the TestChimeraTK2 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "TestChimeraTK2.h"

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::TestChimeraTK2StateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  FAULT    |  
//  RUNNING  |  
//  INIT     |  Server is in init state


namespace TestChimeraTK2_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(TestChimeraTK2::TestChimeraTK2StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TestChimeraTK2::TestChimeraTK2StateAllowed.AdditionalMethods

}	//	End of namespace
