/*----- PROTECTED REGION ID(DeviceImpl.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        DeviceImpl.cpp
//
// description : C++ source for the DeviceImpl class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               DeviceImpl are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include "DeviceImpl.h"
#include "DeviceClass.h"

#include <ChimeraTK/Utilities.h>
#include <ChimeraTK/ControlSystemAdapter/ApplicationFactory.h>
#include <TangoAdapter.h>

#if 0
#include "MyApplication.h"
static ChimeraTK::ApplicationFactory<ExampleApp> theExampleAppFactory;
#endif
/*----- PROTECTED REGION END -----*/	//	DeviceImpl.cpp

/**
 *  DeviceImpl class description:
 *    Test
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

namespace ChimeraTK::TangoAdapter
{
/*----- PROTECTED REGION ID(DeviceImpl::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	DeviceImpl::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::DeviceImpl()
 *	Description : Constructors for a Tango device
 *                implementing the classDeviceImpl
 */
//--------------------------------------------------------
DeviceImpl::DeviceImpl(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(DeviceImpl::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::constructor_1
}
//--------------------------------------------------------
DeviceImpl::DeviceImpl(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(DeviceImpl::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::constructor_2
}
//--------------------------------------------------------
DeviceImpl::DeviceImpl(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(DeviceImpl::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void DeviceImpl::delete_device()
{
	DEBUG_STREAM << "DeviceImpl::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceImpl::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	delete adapter;
	//delete theExampleApp;
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void DeviceImpl::init_device()
{
	DEBUG_STREAM << "DeviceImpl::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceImpl::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	/*----- PROTECTED REGION ID(DeviceImpl::init_device) ENABLED START -----*/
	
	//	Initialize device
    //set DMapFilePath from property
    if (!dMapFilePath.empty())
    {
        ChimeraTK::setDMapFilePath(dMapFilePath);
    }


	adapter = new AdapterImpl(this, attributList);


	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::init_device
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void DeviceImpl::get_device_property()
{
	/*----- PROTECTED REGION ID(DeviceImpl::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("AttributList"));
	dev_prop.push_back(Tango::DbDatum("DMapFilePath"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on DeviceClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		DeviceClass	*ds_class =
			(static_cast<DeviceClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize AttributList from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  attributList;
		else {
			//	Try to initialize AttributList from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  attributList;
		}
		//	And try to extract AttributList value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  attributList;

		//	Try to initialize DMapFilePath from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  dMapFilePath;
		else {
			//	Try to initialize DMapFilePath from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  dMapFilePath;
		}
		//	And try to extract DMapFilePath value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  dMapFilePath;

	}

	/*----- PROTECTED REGION ID(DeviceImpl::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void DeviceImpl::always_executed_hook()
{
	//DEBUG_STREAM << "DeviceImpl::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(DeviceImpl::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void DeviceImpl::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "DeviceImpl::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(DeviceImpl::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::read_attr_hardware
}


//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void DeviceImpl::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(DeviceImpl::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : DeviceImpl::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void DeviceImpl::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(DeviceImpl::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	DeviceImpl::add_dynamic_commands
}

/*----- PROTECTED REGION ID(DeviceImpl::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	DeviceImpl::namespace_ending
} //	namespace
